-- 1. MOSTRAR TODOS LOS REGISTROS DE UNA TABLA RELEVANTE DE TU MODELO.
SELECT * FROM EMPLEADO;

-- 2. SELECCIONAR SOLO ALGUNOS CAMPOS CONCRETOS DE UNA TABLA (NOMBRE Y EMAIL DE CLIENTES).
SELECT NOMBRE, EMAIL FROM CLIENTE;

-- 3. FILTRAR REGISTROS POR UN VALOR EXACTO CON WHERE (ENVÍOS EN TRÁNSITO).
SELECT * FROM ENVIO 
WHERE ESTADO = 'EN TRANSITO';

-- 4. FILTRAR USANDO LIKE PARA BUSCAR UN PATRÓN EN UN CAMPO DE TEXTO (QUE CONTENGA 'IPHONE').
SELECT * FROM PRODUCTO 
WHERE NOMBRE LIKE '%IPHONE%';

-- 5. FILTRAR USANDO LIKE PARA BUSCAR REGISTROS QUE EMPIECEN POR UNA LETRA O PALABRA (EMPIECEN POR 'A').
SELECT * FROM CLIENTE 
WHERE NOMBRE LIKE 'A%';

-- 6. FILTRAR POR UN RANGO DE FECHAS CON BETWEEN (PEDIDOS ENTRE FECHAS CONCRETAS).
SELECT * FROM PEDIDO 
WHERE FECHA BETWEEN '2023-11-01' AND '2023-12-31';

-- 7. FILTRAR POR UN RANGO NUMÉRICO CON BETWEEN (PRODUCTOS CON PRECIO ENTRE 500 Y 1500).
SELECT * FROM PRODUCTO 
WHERE PVP_BASE BETWEEN 500.00 AND 1500.00;

-- 8. FILTRAR POR UNA CONDICIÓN NUMÉRICA MAYOR O MENOR QUE UN VALOR (LÍNEAS CON CANTIDAD MAYOR A 0).
SELECT * FROM LINEA_PEDIDO 
WHERE CANTIDAD > 0;

-- 9. ORDENAR RESULTADOS DE FORMA ASCENDENTE CON ORDER BY (PEDIDOS DEL MÁS ANTIGUO AL MÁS RECIENTE).
SELECT * FROM PEDIDO 
ORDER BY FECHA ASC;

-- 10. ORDENAR RESULTADOS DE FORMA DESCENDENTE CON ORDER BY (PRODUCTOS DE MAYOR A MENOR PRECIO).
SELECT * FROM PRODUCTO 
ORDER BY PVP_BASE DESC;

-- 11. ORDENAR ALFABÉTICAMENTE POR UN CAMPO DE TEXTO (CLIENTES DE LA A A LA Z).
SELECT * FROM CLIENTE 
ORDER BY NOMBRE ASC;

-- 12. ACTUALIZAR UN CAMPO DE UN REGISTRO CONCRETO CON UPDATE (CAMBIAR ESTADO DE UN ENVÍO).
UPDATE ENVIO 
SET ESTADO = 'ENTREGADO' 
WHERE ID_ENVIO = 1;

-- 13. ACTUALIZAR UN CAMPO USANDO WHERE PARA IDENTIFICAR EL REGISTRO (MODIFICAR CORREO DE CLIENTE POR ID).
UPDATE CLIENTE 
SET EMAIL = 'ANA.MARTINEZ.NUEVO@EMAIL.COM' 
WHERE ID_CLIENTE = 1;

-- 14. COMBINAR DOS TABLAS RELACIONADAS CON JOIN Y MOSTRAR CAMPOS DE AMBAS (NOMBRE DE CLIENTE CON SUS PEDIDOS).
SELECT 
    C.ID_CLIENTE,
    C.NOMBRE, 
    C.APELLIDOS, 
    P.ID_PEDIDO, 
    P.FECHA, 
    P.TIPO AS TIPO_PEDIDO
FROM CLIENTE C
INNER JOIN PEDIDO P ON C.ID_CLIENTE = P.ID_CLIENTE_FK;