-- INSERTAR SEDES
INSERT INTO SEDE (ID_SEDE, NOMBRE, TIPO, CIUDAD, DIRECCION) VALUES 
(1, 'TIENDA CENTRAL MADRID', 'TIENDA', 'MADRID', 'GRAN VÍA, 12'),
(2, 'ALMACÉN NORTE', 'ALMACEN', 'BILBAO', 'POLÍGONO INDUSTRIAL, NAVE 4');

-- INSERTAR EMPLEADOS
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE, DNI, EMAIL, FECHA_INCORP, ID_SEDE_FK) VALUES 
(1, 'LAURA GOMEZ', '12345678A', 'LAURA.GOMEZ@EMPRESA.COM', '2022-01-15', 1),
(2, 'CARLOS RUIZ', '87654321B', 'CARLOS.RUIZ@EMPRESA.COM', '2023-05-10', 2);

-- INSERTAR CLIENTES
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, APELLIDOS, EMAIL, PASSWORD, FECHA_NAC) VALUES 
(1, 'ANA', 'MARTINEZ', 'ANA.MART@EMAIL.COM', 'HASHPASSWORD123', '1990-08-20'),
(2, 'LUIS', 'FERNANDEZ', 'LUIS.FER@EMAIL.COM', 'HASHPASSWORD456', '1985-03-12');

-- INSERTAR DIRECCIONES
INSERT INTO DIRECCION (ID_DIRECCION, ID_CLIENTE_FK, CALLE, NUMERO, PISO, CP, CIUDAD, PAIS) VALUES 
(1, 1, 'CALLE DEL PEZ', '4', '2B', '28004', 'MADRID', 'ESPAÑA');

-- INSERTAR CATEGORÍAS Y SUBCATEGORÍAS
INSERT INTO CATEGORIA (ID_CAT, NOMBRE) VALUES 
(1, 'ELECTRÓNICA'),
(2, 'INFORMÁTICA');

INSERT INTO SUBCATEGORIA (ID_SUBCAT, NOMBRE, ID_CAT_FK) VALUES 
(1, 'SMARTPHONES', 1),
(2, 'PORTÁTILES', 2);

-- INSERTAR PRODUCTOS
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, PVP_BASE, ID_SUBCAT_FK) VALUES 
(1, 'IPHONE 13', 799.99, 1),
(2, 'ASUS ZENBOOK', 1199.50, 2);

-- INSERTAR HISTÓRICO DE PRECIOS
INSERT INTO HISTORICO_PRECIO (ID_HISTORICO, ID_PRODUCTO_FK, PRECIO, FECHA_INICIO, FECHA_FIN) VALUES 
(1, 1, 899.99, '2022-09-01', '2023-01-01'),
(2, 1, 799.99, '2023-01-02', NULL);

-- INSERTAR PROMOCIONES
INSERT INTO PROMOCION (ID_PROMO, NOMBRE, DTO_PORCENTAJE, FECHA_INICIO, FECHA_FIN) VALUES 
(1, 'BLACK FRIDAY', 20.00, '2023-11-20', '2023-11-30');

INSERT INTO PRODUCTO_PROMOCION (ID_PRODUCTO_FK, ID_PROMO_FK) VALUES 
(1, 1);

-- INSERTAR PROVEEDORES E HISTÓRICO
INSERT INTO PROVEEDOR (ID_PROVEEDOR, NOMBRE, ID_EMPLEADO_COMERCIAL_FK) VALUES 
(1, 'TECHSUPPLIER SL', 1);

INSERT INTO HISTORICO_PROVEEDOR (ID_CONDICION, ID_PRODUCTO_FK, ID_PROVEEDOR_FK, PRECIO_COSTE, DIAS_ENTREGA, FECHA_INICIO, FECHA_FIN) VALUES 
(1, 1, 1, 650.00, 3, '2023-01-01', NULL);

-- INSERTAR STOCK
INSERT INTO STOCK (ID_SEDE_FK, ID_PRODUCTO_FK, CANTIDAD) VALUES 
(1, 1, 15),
(2, 2, 50);

-- INSERTAR TRANSFERENCIAS
INSERT INTO TRANSFERENCIA (ID_TRANSF, FECHA, ORIGEN_ID_FK, DESTINO_ID_FK, ID_PRODUCTO_FK, CANTIDAD, ID_EMPLEADO_AUTORIZA_FK) VALUES 
(1, '2023-10-15', 2, 1, 2, 5, 2);

-- INSERTAR PEDIDOS
INSERT INTO PEDIDO (ID_PEDIDO, FECHA, TIPO, ID_CLIENTE_FK, ID_SEDE_FK, ID_EMPLEADO_FK) VALUES 
(1, '2023-11-25', 'ONLINE', 1, 2, NULL),
(2, '2023-12-05', 'FISICA', NULL, 1, 1);

-- INSERTAR ENVÍOS
INSERT INTO ENVIO (ID_ENVIO, ID_PEDIDO_FK, ID_ALMACEN_ORIGEN_FK, TRACKING, TRANSPORTISTA, ESTADO, FECHA_ESTIMADA) VALUES 
(1, 1, 2, 'TRK987654321', 'SEUR', 'EN TRANSITO', '2023-11-28');

-- INSERTAR LÍNEAS DE PEDIDO
INSERT INTO LINEA_PEDIDO (ID_LINEA, ID_PEDIDO_FK, ID_PRODUCTO_FK, ID_ENVIO_FK, CANTIDAD, PRECIO_UNITARIO_APLICADO) VALUES 
(1, 1, 1, 1, 1, 639.99), -- CON EL 20% APLICADO
(2, 2, 2, NULL, 1, 1199.50);

-- INSERTAR TICKETS DE INCIDENCIA
INSERT INTO TICKET_INCIDENCIA (ID_TICKET, ASUNTO, DESCRIPCION, FECHA_APER, FECHA_CIERRE, ESTADO, NOTA_RESOLUCION, ID_PEDIDO_FK, ID_EMPLEADO_AGENTE_FK) VALUES 
(1, 'RETRASO EN ENTREGA', 'EL PEDIDO NO HA LLEGADO A TIEMPO', '2023-11-29', NULL, 'ABIERTO', NULL, 1, 1);

-- INSERTAR VALORACIONES
INSERT INTO VALORACION (ID_VALORACION, PUNTUACION, COMENTARIO, COMPRA_VERIFICADA, ID_CLIENTE_FK, ID_PRODUCTO_FK) VALUES 
(1, 5, 'EXCELENTE TELÉFONO, MUY RÁPIDO.', TRUE, 1, 1);

-- INSERTAR MOVIMIENTO DE PUNTOS
INSERT INTO MOVIMIENTO_PUNTOS (ID_MOVIMIENTO, PUNTOS, TIPO, FECHA, ID_CLIENTE_FK, ID_PEDIDO_FK) VALUES 
(1, 64, 'GANADO', '2023-11-25', 1, 1);