DROP DATABASE IF EXISTS NEXSHOP_DB;
CREATE DATABASE NEXSHOP_DB;

USE NEXSHOP_DB;

-- 1. SEDE
CREATE TABLE SEDE (
    ID_SEDE INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    TIPO VARCHAR(20) CHECK (TIPO IN ('TIENDA', 'ALMACEN')),
    CIUDAD VARCHAR(100),
    DIRECCION VARCHAR(200)
);

-- 2. EMPLEADO
CREATE TABLE EMPLEADO (
    ID_EMPLEADO INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DNI VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    FECHA_INCORP DATE,
    ID_SEDE_FK INT,
    FOREIGN KEY (ID_SEDE_FK) REFERENCES SEDE(ID_SEDE)
);

-- 3. CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FECHA_NAC DATE
);

-- 4. DIRECCION
CREATE TABLE DIRECCION (
    ID_DIRECCION INT PRIMARY KEY,
    ID_CLIENTE_FK INT,
    CALLE VARCHAR(150),
    NUMERO VARCHAR(20),
    PISO VARCHAR(20),
    CP VARCHAR(20),
    CIUDAD VARCHAR(100),
    PAIS VARCHAR(100),
    FOREIGN KEY (ID_CLIENTE_FK) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

-- 5. CATEGORIA
CREATE TABLE CATEGORIA (
    ID_CAT INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL
);

-- 6. SUBCATEGORIA
CREATE TABLE SUBCATEGORIA (
    ID_SUBCAT INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ID_CAT_FK INT,
    FOREIGN KEY (ID_CAT_FK) REFERENCES CATEGORIA(ID_CAT)
);

-- 7. PRODUCTO
CREATE TABLE PRODUCTO (
    ID_PRODUCTO INT PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    PVP_BASE DECIMAL(10, 2) CHECK (PVP_BASE > 0),
    ID_SUBCAT_FK INT,
    FOREIGN KEY (ID_SUBCAT_FK) REFERENCES SUBCATEGORIA(ID_SUBCAT)
);

-- 8. HISTORICO_PRECIO
CREATE TABLE HISTORICO_PRECIO (
    ID_HISTORICO INT PRIMARY KEY,
    ID_PRODUCTO_FK INT,
    PRECIO DECIMAL(10, 2) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES PRODUCTO(ID_PRODUCTO)
);

-- 9. PROMOCION
CREATE TABLE PROMOCION (
    ID_PROMO INT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    DTO_PORCENTAJE DECIMAL(5, 2) CHECK (DTO_PORCENTAJE BETWEEN 1 AND 100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);

-- 10. PRODUCTO_PROMOCION
CREATE TABLE PRODUCTO_PROMOCION (
    ID_PRODUCTO_FK INT,
    ID_PROMO_FK INT,
    PRIMARY KEY (ID_PRODUCTO_FK, ID_PROMO_FK),
    FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_PROMO_FK) REFERENCES PROMOCION(ID_PROMO)
);

-- 11. PROVEEDOR
CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR INT PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    ID_EMPLEADO_COMERCIAL_FK INT,
    FOREIGN KEY (ID_EMPLEADO_COMERCIAL_FK) REFERENCES EMPLEADO(ID_EMPLEADO)
);

-- 12. HISTORICO_PROVEEDOR
CREATE TABLE HISTORICO_PROVEEDOR (
    ID_CONDICION INT PRIMARY KEY,
    ID_PRODUCTO_FK INT,
    ID_PROVEEDOR_FK INT,
    PRECIO_COSTE DECIMAL(10, 2),
    DIAS_ENTREGA INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_PROVEEDOR_FK) REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

-- 13. STOCK
CREATE TABLE STOCK (
    ID_SEDE_FK INT,
    ID_PRODUCTO_FK INT,
    CANTIDAD INT CHECK (CANTIDAD >= 0),
    PRIMARY KEY (ID_SEDE_FK, ID_PRODUCTO_FK),
    FOREIGN KEY (ID_SEDE_FK) REFERENCES SEDE(ID_SEDE),
    FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES PRODUCTO(ID_PRODUCTO)
);

-- 14. TRANSFERENCIA
CREATE TABLE TRANSFERENCIA (
    ID_TRANSF INT PRIMARY KEY,
    FECHA DATE,
    ORIGEN_ID_FK INT,
    DESTINO_ID_FK INT,
    ID_PRODUCTO_FK INT,
    CANTIDAD INT,
    ID_EMPLEADO_AUTORIZA_FK INT,
    FOREIGN KEY (ORIGEN_ID_FK) REFERENCES SEDE(ID_SEDE),
    FOREIGN KEY (DESTINO_ID_FK) REFERENCES SEDE(ID_SEDE),
    FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_EMPLEADO_AUTORIZA_FK) REFERENCES EMPLEADO(ID_EMPLEADO)
);

-- 15. PEDIDO
CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY,
    FECHA DATE,
    TIPO VARCHAR(20) CHECK (TIPO IN ('ONLINE', 'FISICA')),
    ID_CLIENTE_FK INT NULL,
    ID_SEDE_FK INT,
    ID_EMPLEADO_FK INT NULL,
    FOREIGN KEY (ID_CLIENTE_FK) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_SEDE_FK) REFERENCES SEDE(ID_SEDE),
    FOREIGN KEY (ID_EMPLEADO_FK) REFERENCES EMPLEADO(ID_EMPLEADO)
);

-- 16. ENVIO
CREATE TABLE ENVIO (
    ID_ENVIO INT PRIMARY KEY,
    ID_PEDIDO_FK INT,
    ID_ALMACEN_ORIGEN_FK INT,
    TRACKING VARCHAR(100),
    TRANSPORTISTA VARCHAR(100),
    ESTADO VARCHAR(50),
    FECHA_ESTIMADA DATE,
    FOREIGN KEY (ID_PEDIDO_FK) REFERENCES PEDIDO(ID_PEDIDO),
    FOREIGN KEY (ID_ALMACEN_ORIGEN_FK) REFERENCES SEDE(ID_SEDE)
);

-- 17. LINEA_PEDIDO
CREATE TABLE LINEA_PEDIDO (
    ID_LINEA INT PRIMARY KEY,
    ID_PEDIDO_FK INT,
    ID_PRODUCTO_FK INT,
    ID_ENVIO_FK INT NULL,
    CANTIDAD INT CHECK (CANTIDAD <> 0),
    PRECIO_UNITARIO_APLICADO DECIMAL(10, 2),
    FOREIGN KEY (ID_PEDIDO_FK) REFERENCES PEDIDO(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_ENVIO_FK) REFERENCES ENVIO(ID_ENVIO)
);

-- 18. TICKET_INCIDENCIA
CREATE TABLE TICKET_INCIDENCIA (
    ID_TICKET INT PRIMARY KEY,
    ASUNTO VARCHAR(150),
    DESCRIPCION TEXT,
    FECHA_APER DATE,
    FECHA_CIERRE DATE NULL,
    ESTADO VARCHAR(20) CHECK (ESTADO IN ('ABIERTO', 'EN GESTION', 'RESUELTO')),
    NOTA_RESOLUCION TEXT NULL,
    ID_PEDIDO_FK INT NULL,
    ID_EMPLEADO_AGENTE_FK INT,
    FOREIGN KEY (ID_PEDIDO_FK) REFERENCES PEDIDO(ID_PEDIDO),
    FOREIGN KEY (ID_EMPLEADO_AGENTE_FK) REFERENCES EMPLEADO(ID_EMPLEADO)
);

-- 19. VALORACION
CREATE TABLE VALORACION (
    ID_VALORACION INT PRIMARY KEY,
    PUNTUACION INT CHECK (PUNTUACION BETWEEN 1 AND 5),
    COMENTARIO TEXT,
    COMPRA_VERIFICADA BOOLEAN,
    ID_CLIENTE_FK INT,
    ID_PRODUCTO_FK INT,
    UNIQUE (ID_CLIENTE_FK, ID_PRODUCTO_FK),
    FOREIGN KEY (ID_CLIENTE_FK) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES PRODUCTO(ID_PRODUCTO)
);

-- 20. MOVIMIENTO_PUNTOS
CREATE TABLE MOVIMIENTO_PUNTOS (
    ID_MOVIMIENTO INT PRIMARY KEY,
    PUNTOS INT,
    TIPO VARCHAR(20) CHECK (TIPO IN ('GANADO', 'CANJEADO')),
    FECHA DATE,
    ID_CLIENTE_FK INT,
    ID_PEDIDO_FK INT,
    FOREIGN KEY (ID_CLIENTE_FK) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_PEDIDO_FK) REFERENCES PEDIDO(ID_PEDIDO)
);